---
title: "Statistical Inference Course Project Part 1"
author: "Katya Demidova"
date: "10 December 2015"
output: html_document
---

Investigate the exponential distribution in R and compare it with the Central Limit Theorem. The exponential distribution can be simulated in R with `rexp(n, lambda)` where `lambda` is the rate parameter. 

The mean of exponential distribution is `1/lambda` and the standard deviation is also `1/lambda`. Set `lambda = 0.2` for all of the simulations. Investigate the distribution of averages of 40 exponentials. Do a thousand simulations.

Illustrate via simulation and associated explanatory text the properties of the distribution of the mean of 40 exponentials.

1. Show the sample mean and compare it to the theoretical mean of the distribution.
2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.
3. Show that the distribution is approximately normal.
In point 3, focus on the difference between the distribution of a large collection of random exponentials and the distribution of a large collection of averages of 40 exponentials.

## Simulate the data

## 1. Show the sample mean and compare it to the theoretical mean of the distribution.

## 2. Show how variable the sample is (via variance) and compare it to the theoretical variance of the distribution.

## 3. Show that the distribution is approximately normal.