from Bio.Blast import NCBIWWW, NCBIXML
from Bio.Seq import Seq


sequence = Seq('TGGGCCTCATATTTATCCTATATACCATGTTCGTATGGTGGCGCGATGTTCTACGTGAATCCACGTTCGAAGGACATCATACCAAAGTCGTACAATTAGGACCTCGATATGGTTTTATTCTGTTTATCGTATCGGAGGTTATGTTCTTTTTTGCTCTTTTTCGGGCTTCTTCTCATTCTTCTTTGGCACCTACGGTAGAG')

# translate(self, table='Standard', stop_symbol='*', to_stop=False, cds=False)
# Turns a nucleotide sequence into a protein sequence

sequence.translate()

# Seq('WASYLSYIPCSYGGAMFYVNPRSKDIIPKSYN*DLDMVLFCLSYRRLCSFLLFF...LR*'
# HasStopCodon(ExtendedIUPACProtein(), '*'))
